### ISSUE TITLE
node, html() is not a function

### ISSUE THREAD

**Issue by cancerberoSgx** [maael/html-chain#7]
I'm running this in node: 
npm install --save html-chain

var html = require('html-chain')
var test = html
    .add('div',

that works but not

var test = html()....

as it is documented in the README.md

**Comment by maael** [comment]
Cheers for noticing this, it seems I introduced this in https://git.io/vr2fb, which caused the browser and module versions to be instantiated as a function and object respectively. I'll fix this so the module version requires the function instantiation the same as the browser version. This will be published as the next major version `3.0.0`.

**Comment by maael** [comment]
Version `3.0.0` has now been released and published - https://github.com/maael/html-chain/releases/tag/v3.0.0 / https://www.npmjs.com/package/html-chain.
